[theme]
base = "dark"
primaryColor = "#D27D2D"
backgroundColor = "#0B0F17"
secondaryBackgroundColor = "#121620"
textColor = "#F0F6FC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"